"""Assemble final summary.md output."""

from typing import Optional


def assemble_summary(
    tldr: str,
    detailed: str,
    works_cited: str,
    similar_research: Optional[str] = None,
) -> str:
    """Assemble the complete summary.md content.

    Format matches Clarity Protocol output:
    - TLDR section
    - Separator
    - Detailed summary
    - Works Cited
    - Similar Research (optional)
    - Footer

    Args:
        tldr: TLDR text (2-3 sentences)
        detailed: Detailed summary with inline citations
        works_cited: Works Cited section (markdown)
        similar_research: Similar Research section (markdown)

    Returns:
        Complete markdown summary
    """
    parts = []

    # TLDR
    parts.append(tldr.strip())
    parts.append("")
    parts.append("---")
    parts.append("")

    # Detailed summary
    parts.append(detailed.strip())
    parts.append("")

    # Works Cited
    if works_cited:
        parts.append(works_cited.strip())
        parts.append("")

    # Similar Research
    if similar_research:
        parts.append(similar_research.strip())
        parts.append("")

    # Footer
    parts.append("---")
    parts.append("")
    parts.append("*Generated by [fold-at-home](https://github.com/clarityprotocol/fold-at-home)*")

    return "\n".join(parts)
